### ISSUE TITLE
Disable cache checkbox isn't working.

### ISSUE THREAD

**Issue by decimoseptimo** [tillkruss/Nginx-FastCGI-Cache#17]
"Automatically flush the cache when content changes" checkbox isn't working.  

I installed, activated, and set 'Cache Zone Path' plugin setting. Opened a given page in chrome incognito, then updated such page in wp-admin, then reloaded  such page in chrome incognito. A MISS ocurred.

So the plugin is emptying the cache, just regardless of that setting.

```### WordPress Environment ###

Home URL: ***
Site URL: ***
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_MX

### Server Environment ###

Server Info: nginx/1.13.3
PHP Version: 7.1.13-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

...

**Comment by tillkruss** [comment]
This isn't a page cache plugin, so that `MISS` is normal.

**Comment by decimoseptimo** [comment]
Hi, I updated the title to correctly state the issue. From what I understand, that checkbox is the on/off switch for the auto-flush. So it is broken, because it always auto-flushes.

**Comment by tillkruss** [comment]
Feel free to submit a PR.
