### ISSUE TITLE
Better Multisite options

### ISSUE THREAD

**Issue by Lunteer** [tillkruss/Nginx-FastCGI-Cache#19]
@tillkruss Thanks for this great plugin.

More of a Feature request than an issue.

Do you have plans to make this plugin more multiple network friendly? Mainly moving the setup to the Network admin (Setting would be a good place) instead of individual sites (tools)?

Again, Thanks for the great plugin

**Comment by tillkruss** [comment]
I'm not planning on adding that feature myself, but I'd of course merge a PR for it.
