### ISSUE TITLE
How to best set 'nginx_cache_path' and 'nginx_auto_purge' programatically?

### ISSUE THREAD

**Issue by michacassola** [tillkruss/Nginx-FastCGI-Cache#21]
I tried adding `add_option('nginx_cache_path', '/run/nginx-cache');` in several places, but could not add that option. Also setting `'nginx_auto_purge'` to `'1'` automatically would be cool. 

I'd really like to automate this and have little to no knowledge of PHP. Any help will be appreciated!

**Comment by tillkruss** [comment]
Hey @michacassola! I don't really maintain this plugin any longer. If you want to submit a PR with modifications, I'm happy to tag a new release on wp.org.

**Comment by hsntgm** [comment]
@tillkruss @michacassola  I developed a new free plugin that _[v2.0.1](https://github.com/psaux-it/nginx-fastcgi-cache-purge-and-preload/releases/tag/v2.0.1)_ is stable now that address the manage **[Nginx FastCGI Cache Purge and Preload](https://github.com/psaux-it/nginx-fastcgi-cache-purge-and-preload)** on wordpress. I used more direct/easy approach maybe it helps to community.

**Comment by michacassola** [comment]
Very nice, but I am on the way to ditch nginx and redis for openlitespeed behind openresty (for IP blocking with crowdsec). I am changing my whole stack. Even the packages I do myself and built a native gnu tool chain and universal package manager. https://github.com/unypkg

Thanks for your work on that plugin! 🤩
