### ISSUE TITLE
Add purge cache option to editors as well

### ISSUE THREAD

**Issue by flamekiller22** [tillkruss/Nginx-FastCGI-Cache#22]
Is there any way for me to edit the plugin files such that I can add the purge option to the wordpress admin bar node for site editors (or people with a specific role) as well. At present only admins are able to access it if I'm not wrong.

**Comment by flamekiller22** [comment]
Haven't worked with php or wordpress much so not very sure of how to change it.

**Comment by tillkruss** [comment]
You'd need to change the `$capability`.
