### ISSUE TITLE
New plugin version

### ISSUE THREAD

**Issue by lucas-oliver-trondsen** [tillkruss/Nginx-FastCGI-Cache#24]
Thank you for this great plugin! It solves the FastCGI cache purging problem in the simplest way, as compared with other similar plugins. This is what we need. The tool that solves a problem in the simplest way possible is the best tool and it will win the race in the long run. Also, in spite of what others suggested, I find it safe if it's used in conjunction with all the common-sense security measures needed when maintaining WordPress websites.

This plugin works perfectly with the latest version of WordPress (6.5.5) and Nginx (1.22.1).

@tillkruss Please consider uploading this plugin as it is to https://wordpress.org/plugins/nginx-cache, with a new version number (1.0.6), so that the users know that it works with the latest version of WordPress and to make this warning disappear:

![untested_warning](https://github.com/tillkruss/Nginx-FastCGI-Cache/assets/70026832/862ed79c-4ca5-4a46-a64a-213bc97f4124)

**Comment by tillkruss** [comment]
Are there not other plugins that will do the same?

**Comment by lucas-oliver-trondsen** [comment]
All the other plugins with similar functionalities are either not supported anymore, like [this one](https://wordpress.org/plugins/snipe-nginx-cache/) or [this one](https://wordpress.org/plugins/nginx-manager/), or are overly complicated, like [this plugin](https://wordpress.org/plugins/fastcgi-cache-purge-and-preload-nginx/) which requires running a bash script at installation, and makes use of commands like `inotifywait` and `setfacl`, starting with the premise that the sysadmin configured different users for PHP-FPM and for the web server, which is rarely done for some illusive security benefits, at the price of causing problems afterwards when performing simple operations like updating the site or purging the cache, or like [this plugin](https://wordpress.org/plugins/nginx-helper/) which involves installing an external Nginx [module](https://github.com/FRiCKLE/ngx_cache_purge), which can cause issues down the road when upgrading Nginx, just to purge the FastCGI cache.

Your plugin solves the FastCGI cache purging problem in the simplest way as compared with all similar plugins, so, it's the best plugin for this job. The fact that it has been installed more than ten thousand times speaks for itself. Many people realize eventually that the simplest solution to a problem is the best, so, sooner or later they adopt it. Simplicity is in fact what made WordPress the best and most popular CMS in the world. You can do with Drupal everything that you do with WordPress, but in general it will take you twice as much time, effort, patience, and sometimes even money.

Why should I install an additional external unofficial module for Nginx, or run a bash script that changes some things on my server, just to purge the FastCGI cache when a page is updated ?

If you continue uploading new versions of this plugin, which I think will rarely need changes to be kept compatible with new WordPress versions, you will make 10,000 people happy and I'll also add a link to your sponsoring page on my website. Reviews like [this one](https://wordpress.org/support/topic/works-with-6-5-3/), or [this one](https://wordpress.org/support/topic/dont-be-fooled-by-lack-of-updates/), or [this review](https://wordpress.org/support/topic/best-and-free-wordpress-cache-plugin/) prove that I'm not the only one enthusiastic about this plugin.

**Comment by arditmorina** [comment]
Yes, as @lucas-oliver-trondsen said, this is one of the best and simplest plugin that does this job perfect, so uploading a new version to remove the warning it will be great, nothing to lose.

**Comment by lucas-oliver-trondsen** [comment]
Please, Till, say yes. You just have to change the version number of the plugin to 1.0.6 and upload it again to  https://wordpress.org/plugins/nginx-cache, since it's compatible with the latest stable versions of WordPress and Nginx. You are like a father to this plugin. Please, don't let it be an orphan!

**Comment by tillkruss** [comment]
I'll tag a new version this week 👍

**Comment by gerhardt-bergmann** [comment]
Thank you very much! The good you do to others will come back to you.

**Comment by lucas-oliver-trondsen** [comment]
Thank you so much for Nginx Cache!
