### ISSUE TITLE
Cache could not be purged. Filesystem API could not be initialized.

### ISSUE THREAD

**Issue by tr33m4n** [tillkruss/Nginx-FastCGI-Cache#3]
Hi there,

I'm getting the following error:

Cache could not be purged. Filesystem API could not be initialized.

Nothing is appearing in the nginx error log. Any idea what's happening/how to debug?

Thanks

**Comment by tr33m4n** [comment]
Never mind, didn't read the readme closely enough!

**Comment by jonathannz** [comment]
I assume what you saw in the readme was this, `  * The [Filesystem API](http://codex.wordpress.org/Filesystem_API) needs to function without asking for credentials.`

How is this actually achieved?

**Comment by tillkruss** [comment]
@jonathannz: What's the exact question?

**Comment by jonathannz** [comment]
My question is, what exactly must I do to ensure the filesystem API is functioning without asking for credentials?

After reading that codex page, I felt none the wiser.

I am using your excellent plug-in on a site, and sometimes it runs just fine, but other times when I click "Clear cache" it comes back with the error the OP mentions. I am trying to determine why that occurs. If it's something to do with the API asking for credentials, I would be grateful to know how I check this, and also why that might change from occurring, to not occurring (why I can sometimes clear the cache, and other times I can't).

Cheers...

**Comment by tillkruss** [comment]
That sounds like a filesystem permissions issue.

The plugin works best with `direct` filesystem setup, but `ssh2`  and the `ftp*` modes should work as well, as long as the permissions are granted [and it's setup](https://hackrepair.com/blog/set-wordpress-ftp-credentials-within-wp-config-php).
