### ISSUE TITLE
Define WP_CACHE

### ISSUE THREAD

**Issue by webaddicto** [tillkruss/Nginx-FastCGI-Cache#5]
The plugin works super perfectly, so first thank you for making it! I use WP-PostViews plugin to count post views and it can use Ajax to count views on cached pages, however it uses Ajax only if the WP_CACHE is defined. In short, if it acknowledges that you're "using" a caching plugin, it uses Ajax to count the views. You can see another user noticed this: https://wordpress.org/support/topic/server-side-cache-not-working/

There may be other plugins that check for WP_CACHE, do you think it would be a good addition to somehow set WP_CACHE to true when the plugin is loaded?

**Comment by tillkruss** [comment]
No, I rather not add `WP_CACHE` to this plugin because the caching is happening on the server level and not on the WordPress level. You are of course free to set the `WP_CACHE` constant on your site.
